name: CI
on:
  push:
    branches:
      - main

jobs:
  continuous-integration:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 7.0.x
          include-prerelease: false

      - name: Run Tests
        run: dotnet test

      - uses: google-github-actions/release-please-action@v3
        with:
          release-type: simple
          include-v-in-tag: false
